# REGRESIÓN LOGÍSTICA CON PESOS

### HIPÓTESIS:
#### Modificar los pesos de cada clase en la función objetivo del clasificador logístico permite mejorar los resultados en problemas de clasificación desbalanceados

In [203]:
# Importamos los paquetes de la libreria sklearn
from sklearn import datasets # Para extraer los datos
from sklearn.preprocessing import StandardScaler # Para escalar los datos
from sklearn.model_selection import train_test_split # Para entrenar los datos
from sklearn.linear_model import LogisticRegression # Para realizar el modelo
# Para obtener la matriz de confusion, la precision, la exactitud y la sensibilidad del modelo
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, recall_score, f1_score, fbeta_score

In [204]:
# Descargamos nuestra dataset de la libreria sklearn
dataset = datasets.load_iris()
# Verificamos el contenido del dataset
print(dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [205]:
# Visualizamos las características del dataset
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [206]:
X = dataset.data
y = dataset.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [207]:
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [208]:
algoritmo = LogisticRegression()

In [209]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [210]:
y_prediccion = algoritmo.predict(X_test)

In [211]:
np.array(y_prediccion)

array([0, 2, 2, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 2, 0, 2, 2, 2, 1, 2, 0,
       1, 2, 2, 2, 2, 0, 2, 0])

In [212]:
np.array(y_test)

array([0, 2, 2, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 2, 0, 2, 2, 2, 1, 2, 0,
       1, 1, 2, 2, 2, 0, 1, 0])

In [213]:
matriz = confusion_matrix(y_test, y_prediccion)
print(matriz)

[[ 9  0  0]
 [ 0  8  2]
 [ 0  0 11]]


In [217]:
precision = precision_score(y_test, y_prediccion, average = 'macro')
exactitud = accuracy_score(y_test, y_prediccion)
sensibilidad = recall_score(y_test, y_prediccion, average = 'macro')
puntajef1 = f1_score(y_test, y_prediccion, average = 'macro')

In [218]:
print('La precision del modelo es de', precision)
print('La exactitud del modelo es de', exactitud)
print('La sensibilidad del modelo es de', sensibilidad)
print('El puntaje F1 del modelo es de', puntajef1)

La precision del modelo es de 0.9487179487179488
La exactitud del modelo es de 0.9333333333333333
La sensibilidad del modelo es de 0.9333333333333332
El puntaje F1 del modelo es de 0.9351851851851851
